import Foundation

/// One-line persona descriptions for the ICML demo.
/// Based on the PrefWiki benchmark's 57 personas.
enum PersonaDescriptions {
    static func short(for personaIndex: Int) -> String {
        descriptions[personaIndex] ?? "PrefWiki persona \(personaIndex)"
    }

    private static let descriptions: [Int: String] = [
        0:  "EV-only driver, raw vegan, no European cars",
        1:  "Wild forager, strict vegan, outdoor explorer",
        2:  "Classical music lover, quiet lifestyle",
        3:  "Natural health advocate, organic vegan, punk music",
        4:  "Budget traveler, hostel fan, street food seeker",
        5:  "Minimalist lifestyle, no clutter, zero waste",
        6:  "Hardcore gamer, competitive FPS enthusiast",
        7:  "Yoga practitioner, plant-based, no stimulants",
        8:  "Gentle fitness, wool allergy, vegan",
        9:  "Home cook, local produce, slow food movement",
        10: "Cyclist commuter, no car travel, urban living",
        11: "Craft beer enthusiast, no commercial brands",
        12: "Audiobook listener, no physical books",
        13: "Night owl, no morning activities",
        14: "Digital nomad, remote-work only",
        15: "Dog owner, animal welfare activist",
        16: "Pescatarian, no red meat",
        17: "Seafood-free, dairy-free diet",
        18: "Homebody, prefers indoor activities",
        19: "Vintage clothing fan, no fast fashion",
        20: "Jazz enthusiast, no pop music",
        21: "Board game player, no video games",
        22: "Science fiction fan, no romance novels",
        23: "Allotment gardener, organic only",
        24: "Gluten-free diet, celiac disease",
        25: "Coffee connoisseur, no instant coffee",
        26: "Landscape photographer, no portrait photography",
        27: "Mild & peaceful, no spicy food, no cardio",
        28: "Vintage car collector, no modern cars",
        29: "Anti-mainstream music, no EDM, vegan",
        30: "Sustainable fashion only, no synthetic fibers",
        31: "Tea ceremony enthusiast, no coffee",
        32: "Rock climber, outdoor adventure seeker",
        33: "Museum curator aesthetic, no modern art",
        34: "Cold weather person, no tropical destinations",
        35: "Podcaster, no video content",
        36: "Safety-first traveler, avoids crime, no heights",
        37: "Crossword puzzle enthusiast, no Sudoku",
        38: "Marathon runner, no team sports",
        39: "Antique furniture collector, no IKEA",
        40: "Beekeeping hobbyist, pollinator garden",
        41: "Stargazer, dark sky parks only",
        42: "Pilates devotee, no high-impact exercise",
        43: "Watercolor artist, no digital art",
        44: "Herbal tea brewer, no black tea",
        45: "Natural living, no synthetic fragrances, no crate training",
        46: "Historical fiction reader, no sci-fi",
        47: "Fermentation hobbyist, sourdough baker",
        48: "Slow traveler, long stays, no package tours",
        49: "Meditation practitioner, silent retreats",
        50: "Plant parent, no cactus or succulents",
        51: "Stand-up comedy fan, no slapstick",
        52: "Vinyl record collector, no streaming",
        53: "Swimming enthusiast, no gym machines",
        54: "Urban sketcher, no still-life painting",
        55: "Night hiker, no daytime trails",
        56: "Strict ketogenic diet",
    ]
}
